### ISSUE TITLE
TypeError: SequelizeDynamo is not a constructor

### ISSUE THREAD

**Issue by thiagobento-goldengatetec** [zxdong262/dynamo-sequelize#6]
Hi,

I'm try run sample to use SequelizeDynamo, but I get this error:

const sequelize = new SequelizeDynamo(
                  ^

TypeError: SequelizeDynamo is not a constructor
    at Object.<anonymous> (/Users/goldengate/Documents/dev/hfocus/projetos/hfocus-lambda-mailer/functions/dataInput-emailValidation/index.js:77:19)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

I copy/paste the sample. Only change "import" to "require"

Sugestions?

**Comment by zxdong262** [comment]
if use require, should be require('dynamo-sequelize').default

**Comment by zxdong262** [comment]
For v1.0.1, you can use `require('dynamo-sequelize')`
